# Generated by Django 3.2.13 on 2023-09-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='bhawan',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
